# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'sedadriverapp' do
  config = use_native_modules!
use_frameworks! :linkage => :static
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        definitions = build_config.build_settings['GCC_PREPROCESSOR_DEFINITIONS']
        definitions = ['$(inherited)'] if definitions.nil?
        definitions = [definitions] if definitions.is_a?(String)
        unless definitions.include?('FMT_USE_CONSTEVAL=0')
          definitions << 'FMT_USE_CONSTEVAL=0'
        end
        build_config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = definitions

        cpp_flags = build_config.build_settings['OTHER_CPLUSPLUSFLAGS']
        cpp_flags = ['$(inherited)'] if cpp_flags.nil?
        cpp_flags = [cpp_flags] if cpp_flags.is_a?(String)
        unless cpp_flags.include?('-DFMT_USE_CONSTEVAL=0')
          cpp_flags << '-DFMT_USE_CONSTEVAL=0'
        end
        build_config.build_settings['OTHER_CPLUSPLUSFLAGS'] = cpp_flags
      end
    end

    fmt_inl = File.join(__dir__, 'Pods', 'fmt', 'include', 'fmt', 'format-inl.h')
    if File.exist?(fmt_inl)
      begin
        File.chmod(0o644, fmt_inl)
        src = File.read(fmt_inl)
        src = src.sub('FMT_STRING("{}{}"), message, SEP', '"{}{}", message, SEP')
        src = src.sub('FMT_STRING("{}{}"), ERROR_STR, error_code', '"{}{}", ERROR_STR, error_code')
        File.write(fmt_inl, src)
      rescue => e
        Pod::UI.warn("fmt patch skipped: #{e}")
      end
    end

    fmt_format_h = File.join(__dir__, 'Pods', 'fmt', 'include', 'fmt', 'format.h')
    if File.exist?(fmt_format_h)
      begin
        File.chmod(0o644, fmt_format_h)
        src = File.read(fmt_format_h)
        src = src.sub(
          '#define FMT_STRING(s) FMT_STRING_IMPL(s, fmt::detail::compile_string, )',
          '#define FMT_STRING(s) (s)'
        )
        File.write(fmt_format_h, src)
      rescue => e
        Pod::UI.warn("fmt format.h patch skipped: #{e}")
      end
    end

  end
end
